import Foundation

enum AppIcons {
    static func icon(for appName: String) -> String {
        switch appName {
        case "kitty", "Alacritty", "iTerm2", "Terminal", "WezTerm", "Ghostty": return ""
        case "Safari", "safari": return "󰀹"
        case "Google Chrome", "Chrome", "Chromium": return ""
        case "Firefox", "Firefox Developer Edition": return ""
        case "Arc": return ""
        case "Brave Browser": return "󰖟"
        case "Code", "Visual Studio Code", "VSCodium": return "󰨞"
        case "Cursor": return "󰨞"
        case "Finder": return ""
        case "Mail", "Mimestream": return ""
        case "Calendar", "Fantastical": return ""
        case "Home": return "󱉑"
        case "Messages": return "󰍦"
        case "Slack": return ""
        case "Discord": return "󰙯"
        case "ChatGPT": return "󰭹"
        case "Claude": return "󰚩"
        case "Telegram": return ""
        case "WhatsApp": return ""
        case "Spotify", "Music": return ""
        case "Notes": return ""
        case "Todoist": return ""
        case "Obsidian": return "󱓷"
        case "Notion": return "󰈚"
        case "Preview": return "󰋩"
        case "Photoshop": return ""
        case "Illustrator": return ""
        case "Figma": return ""
        case "IntelliJ IDEA", "IntelliJ IDEA CE": return ""
        case "PHPStorm": return ""
        case "PyCharm", "PyCharm CE": return ""
        case "WebStorm": return ""
        case "Android Studio": return ""
        case "Xcode": return ""
        case "Docker", "Docker Desktop": return ""
        case "Postman": return "󰘯"
        case "TablePlus", "Sequel Pro", "DBeaver": return ""
        case "VLC", "IINA": return "󰕼"
        case "Zoom", "zoom.us": return "󰍩"
        case "Microsoft Teams": return "󰊻"
        case "System Settings", "System Preferences": return ""
        case "App Store": return ""
        case "TV": return ""
        case "Activity Monitor": return ""
        default: return ""
        }
    }
}
